server:
  port: 8088

cos:
  accessKey: AKIDELLAoHCkmfOxLapmdmldLsEQVQAjsu5K
  secretKey: eFgx3yjKsMl6GHOVXRI5qfZJsxmVDus3
  bucketName: bucket1-1257576234
  regionName: ap-shanghai
  folderName: blog

#logging:
#  config: classpath:log4j2-spring.xml
#  level: INFO

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 1MB
